<?php

require_once "../includes/dbh.inc.php";
function emptyInputLogin($username,$password){
    $result = false;
    if(empty($username) || empty($password)){
        $result = true;
    }  

    return $result;
}

function usernameExists($pdo, $username){
    // sql query
    $query = "SELECT username, password FROM users WHERE username = :username;";
    $statement = $pdo->prepare($query); //  // Prepare the statement to avoid SQL injection
    $statement->bindValue(':username', $username); // // Bind the :username parameter to the actual $username value
    $statement->execute();

    $result = $statement->fetch(PDO::FETCH_ASSOC); // Retrieves the result set generated by a previously executed query.
    return $result;

}

function loginUser($pdo, $username, $password){
    $userExist = usernameExists( $pdo, $username);

    if($userExist === false){
        header("location: ../login.php?error=invalidlogin");
        exit();

    }

    $dbpassword = $userExist["password"];

    if($password !== $dbpassword){
        echo "<p>Invalid username or password</p>";
        header("location: ../login.php");
        exit();
    }
    
    session_start();
    $_SESSION["username"] = $userExist["username"];
    header("location: ../index.php");
    exit();


}